# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				husk = true
				bat = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				tnt_minecart = true
				block_display = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				snow_golem = true
				cod = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				wither_skeleton = true
				vex = true
				salmon = true
				wandering_trader = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.starcatcher]
				fishing_bob = true
				fish = true
				bottle = true

			[light_sources.settings.entities.zombieawareness]
				scent = true

			[light_sources.settings.entities.alexscaves]
				gammaroach = true
				caniac = true
				thrown_ice_cream_scoop = true
				lanternfish = true
				thrown_waste_drum = true
				seeking_arrow = true
				forsaken = true
				tremorzilla = true
				falling_guano = true
				ink_bomb = true
				atlatitan = true
				cinder_brick = true
				moving_metal_block = true
				trilocaris = true
				sugar_staff_hex = true
				watcher = true
				teletor = true
				spinning_peppermint = true
				quarry_smasher = true
				gumbeeper = true
				caramel_cube = true
				soda_bottle_rocket = true
				candicorn = true
				tephra = true
				brainiac = true
				falling_tree_block = true
				depth_charge = true
				notor = true
				magnetron = true
				corrodent = true
				sweetish_fish = true
				crushed_block = true
				extinction_spear = true
				hullbreaker = true
				luxtructosaurus = true
				deep_one_mage = true
				dark_arrow = true
				gumball = true
				gum_worm_segment = true
				radgill = true
				underzealot = true
				wave = true
				magnetic_weapon = true
				submarine = true
				licowitch = true
				gummy_bear = true
				guano = true
				gum_worm = true
				sea_pig = true
				vesper = true
				floater = true
				ferrouslime = true
				dinosaur_spirit = true
				beholder_eye = true
				desolate_dagger = true
				candy_cane_hook = true
				melted_caramel = true
				water_bolt = true
				limestone_spear = true
				tripodfish = true
				deep_one_knight = true
				boundroid_winch = true
				subterranodon = true
				gossamer_worm = true
				deep_one = true
				gloomoth = true
				nucleeper = true
				mine_guardian = true
				burrowing_arrow = true
				mine_guardian_anchor = true
				chest_boat = true
				nuclear_explosion = true
				boat = true
				boundroid = true
				vallumraptor = true
				falling_frostmint = true
				grottoceratops = true
				tremorsaurus = true
				relicheirus = true
				raycat = true
				gingerbread_man = true
				frostmint_spear = true
				nuclear_bomb = true

			[light_sources.settings.entities.tf_dnv]
				twilight_trader = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				warped_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				swamp_enderman = true
				scarab = true
				end_islands_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.vinery]
				mule = true
				dark_cherry_boat = true
				chair = true
				dark_cherry_chest_boat = true
				wandering_winemaker = true

			[light_sources.settings.entities.alexsmobs]
				devils_hole_pupfish = true
				kangaroo = true
				skelewag = true
				blue_jay = true
				bone_serpent_part = true
				catfish = true
				fart = true
				tasmanian_devil = true
				cosmic_cod = true
				centipede_tail = true
				rhinoceros = true
				comb_jelly = true
				vine_lasso = true
				mungus = true
				jerboa = true
				skunk = true
				bunfungus = true
				dropbear = true
				rattlesnake = true
				blobfish = true
				mimicube = true
				snow_leopard = true
				moose = true
				tiger = true
				rocky_roller = true
				rain_frog = true
				cosmaw = true
				mosquito_spit = true
				stradpole = true
				spectre = true
				hemolymph = true
				anaconda = true
				hammerhead_shark = true
				sunbird = true
				triops = true
				gazelle = true
				sea_bear = true
				tarantula_hawk = true
				void_worm_part = true
				void_worm_shot = true
				void_portal = true
				enderiophage = true
				terrapin = true
				platypus = true
				murmur = true
				void_worm = true
				centipede_body = true
				bald_eagle = true
				froststalker = true
				fly = true
				toucan = true
				skreecher = true
				cachalot_whale = true
				tossed_item = true
				bison = true
				pollen_ball = true
				mudskipper = true
				mud_ball = true
				gelada_monkey = true
				murmur_head = true
				cachalot_echo = true
				laviathan = true
				anteater = true
				enderiophage_rocket = true
				endergrade = true
				roadrunner = true
				cockroach_egg = true
				leafcutter_ant = true
				shoebill = true
				lobster = true
				grizzly_bear = true
				squid_grapple = true
				potoo = true
				farseer = true
				centipede_head = true
				flutter = true
				orca = true
				tendon_segment = true
				ice_shard = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				sand_shot = true
				seal = true
				straddler = true
				emu = true
				mimic_octopus = true
				soul_vulture = true
				warped_mosco = true
				guster = true
				caiman = true
				tusklin = true
				underminer = true
				anaconda_part = true
				emu_egg = true
				gorilla = true
				flying_fish = true
				capuchin_monkey = true
				cockroach = true
				komodo_dragon = true
				bone_serpent = true
				mantis_shrimp = true
				seagull = true
				raccoon = true
				giant_squid = true
				alligator_snapping_turtle = true
				hummingbird = true
				straddleboard = true
				warped_toad = true
				frilled_shark = true
				shark_tooth_arrow = true
				sugar_glider = true
				gust = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.furniture]
				canvas = true
				chair = true
				pells = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.brewery]
				beer_elemental = true
				dark_brew = true
				beer_elemental_attack = true

			[light_sources.settings.entities.twilightforest]
				quest_ram = true
				slider = true
				death_tome = true
				loyal_zombie = true
				kobold = true
				redcap_sapper = true
				boar = true
				hydra = true
				lich = true
				thrown_wep = true
				hydra_mortar = true
				unstable_ice_core = true
				mist_wolf = true
				falling_ice = true
				dwarf_rabbit = true
				winter_wolf = true
				charm_effect = true
				fire_beetle = true
				carminite_golem = true
				lower_goblin_knight = true
				helmet_crab = true
				squirrel = true
				king_spider = true
				maze_slime = true
				moonworm_shot = true
				slime_blob = true
				ice_crystal = true
				tiny_bird = true
				lich_bolt = true
				ur_ghast = true
				yeti = true
				lich_bomb = true
				chain_block = true
				rising_zombie = true
				pinch_beetle = true
				harbinger_cube = true
				deer = true
				hedge_spider = true
				thrown_block = true
				lich_minion = true
				carminite_ghastguard = true
				skeleton_druid = true
				slime_beetle = true
				magic_painting = true
				seeker_arrow = true
				ice_snowball = true
				carminite_ghastling = true
				armored_giant = true
				minoshroom = true
				cube_of_annihilation = true
				blockchain_goblin = true
				knight_phantom = true
				swarm_spider = true
				carminite_broodling = true
				nature_bolt = true
				adherent = true
				raven = true
				redcap = true
				wand_bolt = true
				upper_goblin_knight = true
				troll = true
				hostile_wolf = true
				towerwood_borer = true
				thrown_ice = true
				mosquito_swarm = true
				plateau_boss = true
				tome_bolt = true
				stable_ice_core = true
				protection_box = true
				ice_arrow = true
				minotaur = true
				wraith = true
				alpha_yeti = true
				giant_miner = true
				snow_queen = true
				roving_cube = true
				snow_guardian = true
				naga = true
				penguin = true
				bighorn_sheep = true

			[light_sources.settings.entities.farm_and_charm]
				plow = true
				chair = true
				rotten_tomato = true
				cart = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				falling_urn = true
				cannonball = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.malum]
				ascending_block = true
				thrown_gluttony = true
				scythe_boomerang = true
				bound_rite_locus = true
				scythe_maelstrom = true
				spellweavers_locus = true
				natural_spirit = true
				draining_bolt = true
				hex_bolt = true
				etheric_nitrate = true
				seeking_rite_locus = true
				hidden_blade_delayed_impact = true
				vivid_nitrate = true
				entropic_flame_bolt = true
				pneuma_void = true
				sundering_anchor = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
